# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "yo! hannes!"

# A description of your site for meta tag, search engine results.
description: ""

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://hanboy612.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "G-NNNNNNNN"
google_analytics: "G-8CLL41WEPG"

# Site navigation - each item must have a title and a url.
navigation:
  - text: home
    url: /
  - text: stories
    url: /stories/
  - text: portfolio
    url: https://portfolio.hanboy612.com
  - text: about
    url: /about/

# The shortname for your Disqus site to enable comments.
disqus: hanboy612

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Johannes Carlsen all rights reserved. Theme inspired by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: pretty

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
